apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: f1-dashboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: f1-dashboard
                port:
                  number: 80
